In [1]:
!pip install tensorflow==2.4.1 tensorflow-gpu==2.4.1 opencv-python mediapipe sklearn numpy

You should consider upgrading via the 'C:\Users\Mushhead\PycharmProjects\12\venv\Scripts\python.exe -m pip install --upgrade pip' command.


In [2]:
import cv2
import numpy as np
import os
import time
import mediapipe as mp


# 2. Capturing Keypoints using MediaPipe Holistic

In [3]:
import mediapipe as mp
mp_holistic = mp.solutions.holistic # Holistic model
mp_drawing = mp.solutions.drawing_utils # Drawing utilities

In [4]:
def mediapipe_detection(image, model):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # COLOR CONVERSION BGR 2 RGB
    image.flags.writeable = False                  # Image is no longer writeable
    results = model.process(image)                 # Make prediction
    image.flags.writeable = True                   # Image is now writeable 
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR) # COLOR COVERSION RGB 2 BGR
    return image, results

In [5]:
def draw_landmarks(image, results):
    mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_CONTOURS) # Draw face connections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS) # Draw pose connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw right hand connections

In [6]:
def draw_styled_landmarks(image, results):
    # Draw face connections
    mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_CONTOURS, 
                             mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1), 
                             mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
                             ) 
    # Draw pose connections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,
                             mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
                             ) 
    # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                             ) 
    # Draw right hand connections  
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                             ) 

In [9]:
cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = mediapipe_detection(frame, holistic)
        print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)

        # Show to screen
        cv2.imshow('Sign Language Recognizer', image)

        # Break gracefully
        if cv2.waitKey(10) & 0xFF == ord('c'):
            break
    cap.release()
    cv2.destroyAllWindows()



<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

In [11]:
cap.release()
cv2.destroyAllWindows()

In [23]:
len(extract_keypoints(results))

1662

In [ ]:
results

In [ ]:
draw_landmarks(frame, results)

# 3. Extract Keypoint Values

In [13]:
pose = []


In [14]:
pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(132)
face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(1404)
lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)

In [15]:
face


array([ 0.46993133,  0.3344132 , -0.03832367, ...,  0.56510711,
        0.18555579,  0.01461196])

In [16]:
face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(1404)

In [17]:
np.zeros(1404)

array([0., 0., 0., ..., 0., 0., 0.])

In [18]:
def extract_keypoints(results):
    pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(33*4)
    face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(468*3)
    lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
    rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)
    return np.concatenate([pose, face, lh, rh])

In [19]:
result_test = extract_keypoints(results)

In [20]:
result_test

array([ 0.45940191,  0.28318882, -0.8610903 , ...,  0.        ,
        0.        ,  0.        ])

In [21]:
np.save('0', result_test)

In [22]:
np.load('0.npy')

array([ 0.45940191,  0.28318882, -0.8610903 , ...,  0.        ,
        0.        ,  0.        ])

# 4. Setup Folders for Collection


In [24]:
DATA_PATH = os.path.join('signnumpy') 

# Actions that we try to detect
actions = np.array(['hello','help', 'no', 'please','sorry','thanks','yes'])

# Thirty videos worth of data
no_sequences = 30

# Videos are going to be 30 frames in length
sequence_length = 30

In [25]:
for action in actions: 
    for sequence in range(no_sequences):
        try: 
            os.makedirs(os.path.join(DATA_PATH, action, str(sequence)))
        except:
            pass

# 5. Collect Keypoint Values for Training and Testing

In [26]:
cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    
    # NEW LOOP
    # Loop through actions
    for action in actions:
        # Loop through sequences aka videos
        for sequence in range(no_sequences):
            # Loop through video length aka sequence length
            for frame_num in range(sequence_length):

                # Read feed
                ret, frame = cap.read()

                # Make detections
                image, results = mediapipe_detection(frame, holistic)
#                 print(results)
                # Draw landmarks
                draw_styled_landmarks(image, results)
                # NEW Apply wait logic
                if frame_num == 0: 
                    cv2.putText(image, 'STARTING COLLECTION', (120,200), 
                               cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)
                    cv2.waitKey(2000)
                else: 
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)
                
                # NEW Export keypoints
                keypoints = extract_keypoints(results)
                npy_path = os.path.join(DATA_PATH, action, str(sequence), str(frame_num))
                np.save(npy_path, keypoints)

                # Break gracefully
                if cv2.waitKey(10) & 0xFF == ord('c'):
                    cap.release()
                    cv2.destroyAllWindows()
                    break
    cap.release()
    cv2.destroyAllWindows()

In [28]:
cap.release()
cv2.destroyAllWindows()

# 6. Preprocess Data and Create Labels and Features

In [25]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [26]:
label_map = {label:num for num, label in enumerate(actions)}

In [27]:
print(label_map)

{'hello': 0, 'help': 1, 'no': 2, 'please': 3, 'sorry': 4, 'thanks': 5, 'yes': 6}


In [28]:
sequences, labels = [], []
for action in actions:
    for sequence in range(no_sequences):
        window = []
        for frame_num in range(sequence_length):
            res = np.load(os.path.join(DATA_PATH, action, str(sequence), "{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])


In [29]:
np.array(sequences).shape

(210, 30, 1662)

In [30]:
np.array(labels).shape

(210,)

In [31]:
X = np.array(sequences)

In [32]:
X.shape

(210, 30, 1662)

In [33]:
y = to_categorical(labels).astype(int)

In [34]:
y

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05)

In [36]:
y_test.shape

(11, 7)

# 7)Build and Train the LSTM NEURAL NETWORK

In [37]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import TensorBoard

In [38]:
log_dir = os.path.join('Logs')
tb_callback = TensorBoard(log_dir=log_dir)

In [39]:
res = [0.2,0.2,0.7,0.7,0.2,0.2]

In [40]:
model = Sequential()


In [43]:
model.add(LSTM(64, return_sequences=True, activation='relu', input_shape=(30,1662)))
model.add(LSTM(128, return_sequences=True, activation='relu'))
model.add(LSTM(64, return_sequences=False, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(actions.shape[0], activation='softmax'))

In [44]:
actions[np.argmax(res)]

'no'

In [45]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [87]:
model.fit(X_train, y_train, epochs=500, callbacks=[tb_callback])

Epoch 1/500
7/7 [==============================] - 13s 503ms/step - loss: 3.5747 - categorical_accuracy: 0.1607
Epoch 2/500
7/7 [==============================] - 2s 219ms/step - loss: 2.0014 - categorical_accuracy: 0.1050
Epoch 3/500
7/7 [==============================] - 1s 175ms/step - loss: 1.9278 - categorical_accuracy: 0.1175
Epoch 4/500
7/7 [==============================] - 1s 167ms/step - loss: 1.9064 - categorical_accuracy: 0.1734
Epoch 5/500
7/7 [==============================] - 1s 168ms/step - loss: 1.7698 - categorical_accuracy: 0.1733
Epoch 6/500
7/7 [==============================] - 1s 173ms/step - loss: 1.7106 - categorical_accuracy: 0.2348
Epoch 7/500
7/7 [==============================] - 1s 167ms/step - loss: 1.8920 - categorical_accuracy: 0.1694
Epoch 8/500
7/7 [==============================] - 1s 162ms/step - loss: 1.8601 - categorical_accuracy: 0.1287
Epoch 9/500
7/7 [==============================] - 1s 178ms/step - loss: 1.7000 - categorical_accuracy: 0.2806


7/7 [==============================] - 1s 162ms/step - loss: 1.9434 - categorical_accuracy: 0.1591
Epoch 147/500
7/7 [==============================] - 1s 159ms/step - loss: 1.9433 - categorical_accuracy: 0.1488
Epoch 148/500
7/7 [==============================] - 1s 160ms/step - loss: 1.9447 - categorical_accuracy: 0.1569
Epoch 149/500
7/7 [==============================] - 1s 160ms/step - loss: 1.9426 - categorical_accuracy: 0.1812
Epoch 150/500
7/7 [==============================] - 1s 159ms/step - loss: 1.9424 - categorical_accuracy: 0.1624
Epoch 151/500
7/7 [==============================] - 1s 159ms/step - loss: 1.9454 - categorical_accuracy: 0.1322
Epoch 152/500
7/7 [==============================] - 1s 179ms/step - loss: 1.9446 - categorical_accuracy: 0.1536
Epoch 153/500
7/7 [==============================] - 1s 165ms/step - loss: 1.9479 - categorical_accuracy: 0.1497
Epoch 154/500
7/7 [==============================] - 1s 166ms/step - loss: 1.9436 - categorical_accuracy: 0.13

7/7 [==============================] - 1s 163ms/step - loss: 1.9425 - categorical_accuracy: 0.1558
Epoch 291/500
7/7 [==============================] - 1s 157ms/step - loss: 1.9420 - categorical_accuracy: 0.1512
Epoch 292/500
7/7 [==============================] - 1s 162ms/step - loss: 1.9484 - categorical_accuracy: 0.1284
Epoch 293/500
7/7 [==============================] - 1s 177ms/step - loss: 1.9445 - categorical_accuracy: 0.1318
Epoch 294/500
7/7 [==============================] - 1s 159ms/step - loss: 1.9487 - categorical_accuracy: 0.1363
Epoch 295/500
7/7 [==============================] - 1s 156ms/step - loss: 1.9439 - categorical_accuracy: 0.1577
Epoch 296/500
7/7 [==============================] - 1s 158ms/step - loss: 1.9427 - categorical_accuracy: 0.1776
Epoch 297/500
7/7 [==============================] - 1s 159ms/step - loss: 1.9469 - categorical_accuracy: 0.1030
Epoch 298/500
7/7 [==============================] - 1s 159ms/step - loss: 1.9412 - categorical_accuracy: 0.17

7/7 [==============================] - 1s 162ms/step - loss: 1.9471 - categorical_accuracy: 0.1362
Epoch 435/500
7/7 [==============================] - 1s 160ms/step - loss: 1.9437 - categorical_accuracy: 0.1284
Epoch 436/500
7/7 [==============================] - 1s 171ms/step - loss: 1.9414 - categorical_accuracy: 0.1608
Epoch 437/500
7/7 [==============================] - 1s 162ms/step - loss: 1.9430 - categorical_accuracy: 0.1504
Epoch 438/500
7/7 [==============================] - 1s 162ms/step - loss: 1.9447 - categorical_accuracy: 0.1495
Epoch 439/500
7/7 [==============================] - 1s 160ms/step - loss: 1.9422 - categorical_accuracy: 0.1395
Epoch 440/500
7/7 [==============================] - 1s 158ms/step - loss: 1.9459 - categorical_accuracy: 0.1471
Epoch 441/500
7/7 [==============================] - 1s 162ms/step - loss: 1.9422 - categorical_accuracy: 0.1732
Epoch 442/500
7/7 [==============================] - 1s 159ms/step - loss: 1.9489 - categorical_accuracy: 0.11

In [64]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_6 (LSTM)                (None, 30, 64)            442112    
_________________________________________________________________
lstm_7 (LSTM)                (None, 30, 128)           98816     
_________________________________________________________________
lstm_8 (LSTM)                (None, 64)                49408     
_________________________________________________________________
dense_6 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_7 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_8 (Dense)              (None, 7)                 231       
Total params: 596,807
Trainable params: 596,807
Non-trainable params: 0
________________________________________________

# 8. Make Predictions

In [65]:
res = model.predict(X_test)

In [66]:
actions[np.argmax(res[2])]

'sorry'

In [67]:
actions[np.argmax(y_test[2])]

'sorry'

# 9. Save Weights


In [71]:
model.save('action.h5')

In [46]:
model.load_weights('action.h5')

# 10. Evaluation using Confusion Matrix and Accuracy

In [47]:
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score

In [48]:
yhat = model.predict(X_test)

In [49]:
ytrue = np.argmax(y_test, axis=1).tolist()
yhat = np.argmax(yhat, axis=1).tolist()

In [50]:
multilabel_confusion_matrix(ytrue, yhat)

array([[[ 9,  0],
        [ 0,  2]],

       [[10,  0],
        [ 0,  1]],

       [[ 9,  0],
        [ 0,  2]],

       [[ 9,  0],
        [ 0,  2]],

       [[10,  0],
        [ 0,  1]],

       [[ 8,  0],
        [ 0,  3]]], dtype=int64)

In [51]:
accuracy_score(ytrue, yhat)

1.0

# 11. Test in Real Time

In [52]:
# actions=np.delete(actions,0)
actions


array(['hello', 'help', 'no', 'please', 'sorry', 'thanks', 'yes'],
      dtype='<U6')

In [53]:
# # res=np.delete(res,0)
res

[0.2, 0.2, 0.7, 0.7, 0.2, 0.2]

In [54]:
colors = [(148, 0, 211),(75, 0, 130),(0, 0, 255), (0, 255, 0),(255, 255, 0),(255, 127, 0),(255, 0 , 0)]
def prob_viz(res, actions, input_frame, colors):
    output_frame = input_frame.copy()
    for num, prob in enumerate(res):
        print(num,prob,actions[num])
        cv2.rectangle(output_frame, (0,60+num*40), (int(prob*130), 90+num*45), colors[num], -1)
       
        cv2.putText(output_frame, actions[num], (0, 85+num*40), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2, cv2.LINE_AA)
        
    return output_frame

In [56]:
sequence = []
sentence = []
threshold = 0.8
cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():
        # Read feed
        ret, frame = cap.read()
        # Make detections
        image, results = mediapipe_detection(frame, holistic)
        draw_styled_landmarks(image, results)
        print(results)
        # Draw landmarks
#         draw_styled_landmarks(image, results)
        # 2. Prediction logic
        keypoints = extract_keypoints(results)
#         sequence.insert(0,keypoints)
#         sequence = sequence[:30]
        sequence.append(keypoints)
        sequence = sequence[-30:]
        if len(sequence) == 30:
            res = model.predict(np.expand_dims(sequence, axis=0))[0]
            print(actions[np.argmax(res)])  
        #3. Viz logic
            if res[np.argmax(res)] > threshold: 
                if len(sentence) > 0: 
                    if actions[np.argmax(res)] != sentence[-1]:
                        sentence.append(actions[np.argmax(res)])
                else:
                    sentence.append(actions[np.argmax(res)])
            if len(sentence) > 5: 
                sentence = sentence[-5:]
            # Viz probabilities
            image = prob_viz(res, actions, image, colors)
#         cv2.rectangle(image, (0,0), (640, 40), (245, 117, 16), -1)
#         cv2.putText(image, ' '.join(sentence), (3,30), 
#                        cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
        # Show to screen
        cv2.imshow('OpenCV Feed', image)
        # Break gracefully
        if cv2.waitKey(10) & 0xFF == ord('c'):
            break
    cap.release()
    cv2.destroyAllWindows()

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

<class 'mediapipe.python.solution_base.SolutionOutputs'>
hello
0 0.87871426 hello
1 1.0235078e-14 help
2 0.12128575 no
3 1.0035382e-08 please
4 1.500018e-08 sorry
5 3.8450322e-16 thanks
6 1.1892031e-13 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
hello
0 0.98197514 hello
1 1.0598836e-13 help
2 0.018024763 no
3 3.9061285e-10 please
4 1.6393383e-07 sorry
5 4.2638483e-14 thanks
6 2.7131455e-12 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
no
0 0.15856667 hello
1 8.669192e-12 help
2 0.841432 no
3 1.3766626e-06 please
4 4.440087e-08 sorry
5 7.3681275e-14 thanks
6 5.394921e-12 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
hello
0 0.8453089 hello
1 4.9946415e-11 help
2 0.15469009 no
3 4.7672184e-08 please
4 1.0428031e-06 sorry
5 9.1749195e-12 thanks
6 1.9314407e-10 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
no
0 0.4392213 hello
1 1.346661e-09 help
2 0.5607751 no
3 9.874286e-07 please
4 2.6949872e-06 sorry
5 7.332118e-11 thanks
6 

<class 'mediapipe.python.solution_base.SolutionOutputs'>
no
0 0.0018201302 hello
1 0.0079154065 help
2 0.60737413 no
3 0.0007590471 please
4 0.37735027 sorry
5 0.00035969444 thanks
6 0.0044212868 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
no
0 0.0014861183 hello
1 0.0050049275 help
2 0.6704753 no
3 0.00032174186 please
4 0.31813326 sorry
5 0.0003823659 thanks
6 0.0041964236 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
no
0 0.0007985545 hello
1 0.0018456011 help
2 0.51583666 no
3 6.1608276e-05 please
4 0.47223505 sorry
5 0.0006159694 thanks
6 0.008606642 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
sorry
0 0.0014884197 hello
1 0.0015726282 help
2 0.113176204 no
3 0.0009787811 please
4 0.8777558 sorry
5 0.00022769356 thanks
6 0.0048004254 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
sorry
0 0.00028426474 hello
1 0.00073998835 help
2 0.18454644 no
3 2.5465535e-05 please
4 0.7988522 sorry
5 0.0005080487 thanks
6 0.015043586 

<class 'mediapipe.python.solution_base.SolutionOutputs'>
please
0 0.0005562437 hello
1 9.8214965e-05 help
2 0.16498013 no
3 0.83436525 please
4 2.7414804e-09 sorry
5 2.6516268e-08 thanks
6 1.6683339e-07 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
please
0 0.0007900091 hello
1 7.063054e-05 help
2 0.1788403 no
3 0.82029897 please
4 4.147805e-09 sorry
5 2.8114544e-08 thanks
6 1.204987e-07 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
please
0 0.0016546563 hello
1 0.00010731537 help
2 0.28502318 no
3 0.7132144 please
4 1.3045608e-08 sorry
5 6.451325e-08 thanks
6 3.0383842e-07 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
no
0 0.009135793 hello
1 3.1282063e-06 help
2 0.96367824 no
3 0.027182614 please
4 9.16493e-08 sorry
5 6.736159e-09 thanks
6 1.05905606e-07 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
no
0 0.011269461 hello
1 6.9854623e-06 help
2 0.9195578 no
3 0.06916536 please
4 1.1054867e-07 sorry
5 2.207436e-08 thanks
6 2.

<class 'mediapipe.python.solution_base.SolutionOutputs'>
no
0 0.22014304 hello
1 1.0002424e-09 help
2 0.779842 no
3 1.32233135e-05 please
4 1.6857987e-06 sorry
5 2.6672442e-11 thanks
6 1.2468939e-09 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
hello
0 0.9453418 hello
1 9.404377e-12 help
2 0.054656435 no
3 7.113775e-08 please
4 1.6108908e-06 sorry
5 1.4049351e-12 thanks
6 1.3165523e-10 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
hello
0 0.89236885 hello
1 5.880167e-13 help
2 0.10763094 no
3 8.592099e-08 please
4 7.237771e-08 sorry
5 1.2428183e-14 thanks
6 3.1018725e-12 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
hello
0 0.9972638 hello
1 1.5651927e-14 help
2 0.002735917 no
3 1.7193134e-10 please
4 2.675047e-07 sorry
5 1.585026e-15 thanks
6 1.0942731e-12 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
hello
0 0.97314894 hello
1 5.4328614e-16 help
2 0.02685111 no
3 1.5790934e-09 please
4 1.6695293e-09 sorry
5 3.6431066e-19 tha

<class 'mediapipe.python.solution_base.SolutionOutputs'>
yes
0 4.8909843e-10 hello
1 3.7823787e-07 help
2 3.1391597e-08 no
3 9.95518e-13 please
4 0.000112594724 sorry
5 1.657059e-05 thanks
6 0.9998704 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
yes
0 3.8666172e-09 hello
1 1.432099e-06 help
2 7.693295e-09 no
3 1.0228474e-12 please
4 0.00018344744 sorry
5 3.062249e-05 thanks
6 0.9997845 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
yes
0 1.3150286e-08 hello
1 2.7195301e-06 help
2 1.6485198e-07 no
3 8.289187e-11 please
4 0.0015451686 sorry
5 2.0729949e-05 thanks
6 0.99843115 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
yes
0 8.101125e-09 hello
1 1.985413e-06 help
2 1.3579207e-08 no
3 1.6363754e-12 please
4 0.0001333237 sorry
5 5.830917e-05 thanks
6 0.99980634 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
yes
0 1.8423029e-07 hello
1 1.7765426e-05 help
2 1.0199592e-06 no
3 3.0357845e-09 please
4 0.011869788 sorry
5 4.164113e-05 

<class 'mediapipe.python.solution_base.SolutionOutputs'>
no
0 0.48988387 hello
1 3.1855902e-09 help
2 0.50452065 no
3 2.2305073e-08 please
4 0.0055954815 sorry
5 7.5502216e-10 thanks
6 4.7824866e-08 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
no
0 0.21387665 hello
1 2.1297089e-08 help
2 0.7819833 no
3 3.5692146e-06 please
4 0.00413648 sorry
5 4.8001894e-11 thanks
6 4.4437257e-08 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
no
0 0.010298092 hello
1 2.6733217e-08 help
2 0.94291526 no
3 4.5253636e-09 please
4 0.04678647 sorry
5 4.7015136e-10 thanks
6 1.0235993e-07 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
no
0 0.01966027 hello
1 8.93885e-08 help
2 0.8799542 no
3 1.6891453e-06 please
4 0.10038365 sorry
5 2.9960603e-11 thanks
6 1.5412343e-07 yes
<class 'mediapipe.python.solution_base.SolutionOutputs'>
sorry
0 0.0008431566 hello
1 1.0524024e-08 help
2 0.2118374 no
3 4.5655413e-10 please
4 0.7873192 sorry
5 5.5589106e-10 thanks
6 2.6180712e-